// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptReceivedFile(arg1:string,arg2:string,arg3:Array<number>):Promise<Array<any>>;

export function EncryptAndPrepareFile(arg1:any):Promise<Record<string, any>>;

export function SaveDownloadedFile(data:Array<number>, defaultFilename:string):Promise<void>;
