// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptReceivedFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptReceivedFile'](arg1, arg2, arg3);
}

export function EncryptAndPrepareFile(arg1) {
  return window['go']['main']['App']['EncryptAndPrepareFile'](arg1);
}

export function SaveDownloadedFile(data, defaultFilename) {
  return window['go']['main']['App']['SaveDownloadedFile'](data, defaultFilename);
}
